### ISSUE TITLE
Falha na conversão nos coletores do Firebird para MySQL

### ISSUE THREAD

**Issue by edvaldoszy** [utfpr/hcf-web#33]
## Technical info

Na tentativa de conversão do banco de dados do Firebird para o MySQL utilizando o sctip Python, recebi o seguinte erro no terminal.

```shell
Creating table historico_acessos: OK
Creating table configuracao: OK
Creating table coletores: OK
Creating table relevos: OK
Creating table solos: OK
Creating table vegetacoes: OK
Creating table fase_sucessional: OK
Creating table paises: OK
Creating table estados: OK
Creating table cidades: OK
Creating table locais_coleta: OK
Creating table familias: OK
Creating table generos: OK
Creating table autores: OK
Creating table especies: OK
Creating table variedades: OK
Creating table sub_especies: OK
Creating table sub_familias: OK
Creating table colecoes_anexas: OK
Creating table enderecos: OK
Creating table herbarios: OK
Creating table telefones: OK
Creating table remessas: OK
Creating table tipos: OK
Creating table identificadores: OK
Creating table tombos: OK
Creating table tombos_coletores: OK
Creating table tombos_identificadores: OK
Creating table tombos_fotos: OK
Creating table tombo_alteracoes_antigas: OK
Creating table retirada_exsiccata_tombos: OK
Creating table tipos_usuarios: OK
Creating table usuarios: OK
Creating table alteracoes: OK
Processando Coletores! Aguarde...
Geting table content coletor: Geting table content tombo: Geting table content tombo: Traceback (most recent call last):
  File "conversao.py", line 1537, in <module>
    main()
  File "conversao.py", line 885, in main
    commitColetorData = (idColetor, coletor[1], None, numero[1], dataAtual, 1)
IndexError: string index out of range
```

O bando de dados utilizado está anexado aqui: https://drive.google.com/file/d/17_wi5EPhc_3-jWzWQAIPrlVcb_WcmXMd/view?usp=drive_link

**Comment by edvaldoszy** [comment]
Configuração errada do banco de dados causou o problema. O script está funcionando corretamente.
